name: kravr
description: A food tracking app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/Google-pin.jpg